### PR TITLE
increment version after new steam HTTPs fix

### PR DESCRIPTION
**Pull request by Deekor**

### CODE REVIEW

**Comment by potato20** [comment]
@reu is there anything holding up deployment of new version?

**Comment by timwis** [comment]
*bump* this plugin is broken without this fix :(

**Comment by reu** [comment]
Sorry for the delay, I am really not maintaining this project anymore. I am going to open a issue for possible new maintainers.

**Comment by potato20** [comment]
I'd be happy to maintain it since I'm actively working with this.

**Pull request merged**
